In [1]:
import numpy as np

arr = np.array([5,6,7,8,9])
print(arr)


[5 6 7 8 9]


In [2]:
matrix = np.array([[1, 2, 3, 4], [4, 5, 6, 5], [7, 8, 9, 5]])
print(matrix)


[[1 2 3 4]
 [4 5 6 5]
 [7 8 9 5]]


In [3]:
zeros = np.zeros((3, 3))  # 3x3 array of zeros
ones = np.ones((2, 2))    # 2x2 array of ones
eye = np.eye(3)           # 3x3 identity matrix
print(zeros)
print(ones)
print(eye)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
ones = np.ones((2, 2)) 
print(ones)

[[1. 1.]
 [1. 1.]]


In [5]:
eye = np.eye(3) 
print(eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
zeros = np.zeros((3, 3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
arr = np.arange(0, 50, 5)  # Array from 0 to 9 with step of 2
print(arr)

[ 0  5 10 15 20 25 30 35 40 45]


In [8]:
arr = np.linspace(0, 50, 5)  # 5 evenly spaced values from 0 to 1
print(arr)


[ 0.  12.5 25.  37.5 50. ]


In [9]:
arr = np.array([1, 2, 3, 4])
print(arr + 2)  # Add 2 to each element
print(arr * 3)  # Multiply each element by 3


[3 4 5 6]
[ 3  6  9 12]


In [10]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

product = np.dot(matrix1, matrix2)
print(product)


[[19 22]
 [43 50]]


In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1])      
print(arr[0:3])    


20
[10 20 30]


In [ ]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix[1, 2])   
print(matrix[2,:])  


6
[7 8 9]


In [13]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix[1, 2])   # Access the element at the second row, third column
print(matrix[2,:])   # Access all rows of the second column


6
[7 8 9]


In [14]:
arr = np.arange(1, 10)
reshaped = arr.reshape((3, 3))  # Reshape to 3x3 matrix
print(reshaped)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
transposed = reshaped.T
print(transposed)


[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [16]:
arr = np.array([1, 2, 3])
matrix = np.array([[1], [2], [3]])

result = arr + matrix
print(result)


[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [ ]:
random_arr = np.random.rand(3, 3)  
print(random_arr)

random_int_arr = np.random.randint(0, 10, (3, 3))  
print(random_int_arr)


[[0.08279683 0.00129666 0.80525295]
 [0.29194504 0.47848092 0.92747022]
 [0.05912885 0.86444609 0.782383  ]]
[[6 4 3]
 [8 3 5]
 [9 3 2]]
